In [1]:
import pandas as pd
import numpy as np
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC

In [2]:
df = pd.read_csv("heart.csv")

In [3]:
df

Age Sex ChestPainType  RestingBP  Cholesterol  FastingBS RestingECG  \
0     40   M           ATA        140          289          0     Normal   
1     49   F           NAP        160          180          0     Normal   
2     37   M           ATA        130          283          0         ST   
3     48   F           ASY        138          214          0     Normal   
4     54   M           NAP        150          195          0     Normal   
..   ...  ..           ...        ...          ...        ...        ...   
913   45   M            TA        110          264          0     Normal   
914   68   M           ASY        144          193          1     Normal   
915   57   M           ASY        130          131          0     Normal   
916   57   F           ATA        130          236          0        LVH   
917   38   M           NAP        138          175          0     Normal   

     MaxHR ExerciseAngina  Oldpeak ST_Slope  HeartDisease  
0      172              N      0.0       Up             0  
1      156              N      1.0     Flat             1  
2       98              N      0.0       Up             0  
3      108              Y      1.5     Flat             1  
4      122              N      0.0       Up             0  
..     ...            ...      ...      ...           ...  
913    132              N      1.2     Flat             1  
914    141              N      3.4     Flat             1  
915    115              Y      1.2     Flat             1  
916    174              N      0.0     Flat             1  
917    173              N      0.0       Up             0  

[918 rows x 12 columns]

In [4]:
df = pd.get_dummies(df,drop_first=True)

In [5]:
df

Age  RestingBP  Cholesterol  FastingBS  MaxHR  Oldpeak  HeartDisease  \
0     40        140          289          0    172      0.0             0   
1     49        160          180          0    156      1.0             1   
2     37        130          283          0     98      0.0             0   
3     48        138          214          0    108      1.5             1   
4     54        150          195          0    122      0.0             0   
..   ...        ...          ...        ...    ...      ...           ...   
913   45        110          264          0    132      1.2             1   
914   68        144          193          1    141      3.4             1   
915   57        130          131          0    115      1.2             1   
916   57        130          236          0    174      0.0             1   
917   38        138          175          0    173      0.0             0   

     Sex_M  ChestPainType_ATA  ChestPainType_NAP  ChestPainType_TA  \
0        1                  1                  0                 0   
1        0                  0                  1                 0   
2        1                  1                  0                 0   
3        0                  0                  0                 0   
4        1                  0                  1                 0   
..     ...                ...                ...               ...   
913      1                  0                  0                 1   
914      1                  0                  0                 0   
915      1                  0                  0                 0   
916      0                  1                  0                 0   
917      1                  0                  1                 0   

     RestingECG_Normal  RestingECG_ST  ExerciseAngina_Y  ST_Slope_Flat  \
0                    1              0                 0              0   
1                    1              0                 0              1   
2                    0              1                 0              0   
3                    1              0                 1              1   
4                    1              0                 0              0   
..                 ...            ...               ...            ...   
913                  1              0                 0              1   
914                  1              0                 0              1   
915                  1              0                 1              1   
916                  0              0                 0              1   
917                  1              0                 0              0   

     ST_Slope_Up  
0              1  
1              0  
2              1  
3              0  
4              1  
..           ...  
913            0  
914            0  
915            0  
916            0  
917            1  

[918 rows x 16 columns]

In [6]:
X = df.drop("HeartDisease",axis="columns")

In [7]:
y = df.HeartDisease

In [8]:
df.isnull().sum() ## hiç nan verimiz yok o yüzden veri temizlemekle uğraşmayacağız.

Age                  0
RestingBP            0
Cholesterol          0
FastingBS            0
MaxHR                0
Oldpeak              0
HeartDisease         0
Sex_M                0
ChestPainType_ATA    0
ChestPainType_NAP    0
ChestPainType_TA     0
RestingECG_Normal    0
RestingECG_ST        0
ExerciseAngina_Y     0
ST_Slope_Flat        0
ST_Slope_Up          0
dtype: int64

In [9]:
X_train , X_test , y_train , y_test = train_test_split(X,y,test_size=0.2,random_state=15)

In [10]:
model1 = LogisticRegression(max_iter=1000)

In [11]:
model1.fit(X_train,y_train)

LogisticRegression(max_iter=1000)

In [12]:
model1.score(X_test,y_test)

0.8369565217391305

In [13]:
model2 = RandomForestClassifier(n_estimators=200)

In [14]:
model2.fit(X_train,y_train)

RandomForestClassifier(n_estimators=200)

In [15]:
model2.score(X_test,y_test)

0.8532608695652174

In [16]:
model3 = SVC(C=3.0,kernel="linear")

In [17]:
model3.fit(X_train,y_train)

SVC(C=3.0, kernel='linear')

In [18]:
model3.score(X_test,y_test)

0.8260869565217391

In [19]:
Scale = StandardScaler()

In [20]:
X_scaled = Scale.fit_transform(X)

In [21]:
X_scaled

array([[-1.4331398 ,  0.41090889,  0.82507026, ..., -0.8235563 ,
        -1.00218103,  1.15067399],
       [-0.47848359,  1.49175234, -0.17196105, ..., -0.8235563 ,
         0.99782372, -0.86905588],
       [-1.75135854, -0.12951283,  0.7701878 , ..., -0.8235563 ,
        -1.00218103,  1.15067399],
       ...,
       [ 0.37009972, -0.12951283, -0.62016778, ...,  1.21424608,
         0.99782372, -0.86905588],
       [ 0.37009972, -0.12951283,  0.34027522, ..., -0.8235563 ,
         0.99782372, -0.86905588],
       [-1.64528563,  0.30282455, -0.21769643, ..., -0.8235563 ,
        -1.00218103,  1.15067399]])

In [22]:
pca = PCA(n_components=4)

In [23]:
X_pca = pca.fit_transform(X_scaled)

In [24]:
X_pca

array([[ 3.1402363 , -0.42349903, -0.64566398, -1.35155372],
       [ 0.23236574, -1.0901533 , -0.77838552,  2.32953364],
       [ 1.65293843,  2.15351147, -0.30496897, -1.83540763],
       ...,
       [-1.74810168, -1.48846612,  0.33748499, -0.56080289],
       [ 1.10315455,  0.20749702, -1.7573308 , -0.39225817],
       [ 2.52724328, -0.47874135,  0.95290819,  1.68658332]])

In [25]:
pca.explained_variance_ratio_

array([0.22586656, 0.11008684, 0.0946602 , 0.08202286])

In [26]:
pca.n_components_

4

In [27]:
X_train_pca , X_test_pca , y_train , y_test = train_test_split(X_pca,y,test_size=0.2,random_state=15)

In [28]:
model1.fit(X_train_pca,y_train)

LogisticRegression(max_iter=1000)

In [29]:
model1.score(X_test_pca,y_test)

0.8532608695652174

In [30]:
model2.fit(X_train_pca,y_train)

RandomForestClassifier(n_estimators=200)

In [31]:
model2.score(X_test_pca,y_test)

0.8586956521739131

In [32]:
model3.fit(X_train_pca,y_train)

SVC(C=3.0, kernel='linear')

In [33]:
model3.score(X_test_pca,y_test)

0.8586956521739131