In [34]:
import pandas as pd
import numpy as np
import pickle ## model kaydetmek için kütüphane
from sklearn import linear_model
import joblib

In [35]:
data = pd.read_csv("canada_per_capita_income.csv")

In [36]:
model = linear_model.LinearRegression()

In [37]:
data.columns = ("year","income")

In [38]:
data[:5]

year       income
0  1970  3399.299037
1  1971  3768.297935
2  1972  4251.175484
3  1973  4804.463248
4  1974  5576.514583

In [39]:
new_df = data.drop("income",axis="columns")

In [40]:
model.fit(new_df,data.income)

LinearRegression()

In [41]:
model.predict([[2020]])

array([41288.69409442])

Modelimiz oluştuğuna göre şimdi kaydedebiliriz

In [42]:
with open('model_pickle','wb') as f:
    pickle.dump(model,f) ## file pointer ile yazma modunda bir file açıp içine modelimizi dump ettik.

In [43]:
with open('model_pickle','rb') as f:
    model2 = pickle.load(f)

In [44]:
model2.predict([[2020]])

array([41288.69409442])

Joblib ile kaydetmenin avantajı büyük miktarda numpy array içeriyorsa daha avantajlı

In [45]:
joblib.dump(model,"model_joblib")

['model_joblib']

In [46]:
mj = joblib.load("model_joblib")

In [47]:
mj.predict([[2020]])

array([41288.69409442])